### ISSUE TITLE
data

### ISSUE THREAD

**Issue by oopsie1412** [gidoBOSSftw5731/covid-19-scraper#2]
do you guys put all your data in a spreadsheet or something like that?

**Comment by DrAlienTech** [comment]
no, it is stored in a postgresql database and retrieved in a process involving protobufs and http requests

**Comment by oopsie1412** [comment]
ok, thanks!

**Comment by DrAlienTech** [comment]
that guy wakes up at 5pm i have no expectations

**Comment by oopsie1412** [comment]
its mostly cause i force him to stay up and play minecraft with me lol

**Comment by DrAlienTech** [comment]
i heard haha

> ok I fixed the api while playing minecraft

**Comment by oopsie1412** [comment]
nice

**Comment by gidoBOSSftw5731** [comment]
Resolved
