### ISSUE TITLE
Discord bot responds to blank !

### ISSUE THREAD

**Issue by oopsie1412** [gidoBOSSftw5731/covid-19-scraper#7]
Whenever I type a blank exclamation point, the bot responds. It's kind-of an unnecessary feature and bugs a lot of people in my server. Can you either make this an opt-out feature or remove it entirely?  
![image](https://user-images.githubusercontent.com/55986805/79159662-7d647480-7da6-11ea-8a4c-aec1879285d1.png)

**Comment by DrAlienTech** [comment]
I'll remove that right now! I originally wanted to add some extra conditionals to see if the user was trying to enter a command but made a mistake but I'll just leave it out for now

**Comment by DrAlienTech** [comment]
Done!
